#ifndef __INCUBATOR_H
#define __INCUBATOR_H
#include "real_time_clock.h"

#define CHICK_EG_INCUBATION_DAYS 21
#define CHICK_EG_TEMPERATURE 378  //37.8c , DHT SENDS READINGS LIKE 378
#define CHICK_EG_RELATIVE_HUMIDITY 87
#define CHICK_EG_RELATIVE_HUMIDITY_LAST_3_DAYS 90

#define TIME_TO_SPINNG_IN_HOURS 6
#define SPINNIG_DURATION_IN_MINUTES 36


void run_incubator();

#endif